# from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
# S3 = S3RemoteProvider(
#     access_key_id=config["key"],
#     secret_access_key=config["secret"],
#     host=config["host"],
#     stay_on_remote=False
# )

prefix = config["prefix"]
# filename = config["filename"]

rule get_MultiAssay:
    input:
        prefix + 'processed/expr_list.rds',
        prefix + 'processed/gene_annotation.csv',
        prefix + 'processed/tx_annotation.csv',
        prefix + 'processed/rnaseq_samples.csv',
        prefix + 'processed/acgh_assay_data.rds',
        prefix + 'processed/acgh_samples.csv'
    output:
        prefix + 'TCL38_MultiAssayExp.rds'
    shell:
        """
        Rscript scripts/get_multiassay.R \
        {prefix}processed \
        {prefix}
        """

rule process_expr:
    input:
        prefix + 'rnaseq/rnaseq.zip',
        prefix + 'rnaseq/Gencode.v33.annotation.RData',
        prefix + 'rnaseq/rnaseq_sample_summary.csv'
    output:
        prefix + 'processed/expr_list.rds',
        prefix + 'processed/gene_annotation.csv',
        prefix + 'processed/tx_annotation.csv',
        prefix + 'processed/rnaseq_samples.csv'
    shell:
        """
        Rscript scripts/process_rnaseq.R \
        {prefix}rnaseq \
        {prefix}processed
        """

rule process_acgh:
    input:
        prefix + 'acgh/acgh.zip'
    output:
        prefix + 'processed/acgh_assay_data.rds',
        prefix + 'processed/acgh_samples.csv'
    shell:
        """
        Rscript scripts/process_acgh.R \
        {prefix}acgh \
        {prefix}processed
        """
